module.exports = {
  env: "development",
  serverPort: 3000,
  secret: "7Wa$5&3W4z9Z-gTs",
  preName: "_trampobom_",
  corsOptions: {
    allowedHeaders: [
      "Origin",
      "X-Requested-With",
      "Content-Type",
      "Accept",
      "X-Access-Token",
      "Authorization",
    ],
    credentials: true,
    methods: "GET,HEAD,OPTIONS,PUT,PATCH,POST,DELETE",
    origin: "http://localhost:3000",
    preflightContinue: false,
  },
  dbHost: "127.0.0.1",
  dbPort: 27017,
  dbUser: "teste",
  dbPass: "12345678",
  dbName: "trampobomdb",
  viewPathLayout: "/src/views/layouts",
  viewPartials: "/src/views/partials",
  viewPath: "/src/views",
  assetsPath: "/src/public/",
};
